export { default as home } from './homeRouter'
export { default as registerSeller } from './registerSellerRouter'
export { default as registerCustomer } from './registerCustomerRouter'
export { default as login } from './loginRouter'
export { default as products } from './productsRouter'